import json, re, html
from pathlib import Path
root=Path(__file__).resolve().parents[1]
out=root/'dist'
original=(out/'app.js').read_text()
data=[
dict(slug='african-parrots',name='African parrots',tag='Intelligence, in every feather.',example='African grey parrot',life='Several decades',lifetext='African parrots are a diverse group. African greys can be long-lived, while Senegal and Meyer’s parrots have different life expectations. Published figures vary substantially; identify the exact species and plan for decades of care.',temperament='Observant and responsive, with individual differences in confidence and sociability. African greys often benefit from predictable routines; smaller African species have their own distinct personalities.',diet='Use a balanced, species-appropriate feeding plan with suitable formulated food and fresh produce. Discuss calcium and overall nutrition with an avian vet, particularly for African greys.',space='Provide room to move, climb and exercise, alongside safe supervised time outside the enclosure. Offer different perch sizes and rotate suitable chew and foraging toys.',noise='Calls and mimicry vary by species and individual. No bird is guaranteed to talk or remain quiet.',fit='A household ready to offer consistent interaction, enrichment and a calm routine.',examples='African grey, Timneh, Senegal and Meyer’s parrots'),
dict(slug='macaws',name='Macaws',tag='Extraordinary colour. Unmistakable presence.',example='Blue-and-gold macaw',life='A long-term commitment',lifetext='Large macaws can live for several decades. Smaller macaw species have different life expectations. Age, nutrition, health and husbandry all influence lifespan; plan for long-term care and a backup caregiver.',temperament='Inquisitive, expressive birds that can enjoy social activity and positive-reinforcement training. Their strong beaks and size call for confident, respectful handling.',diet='Offer suitable formulated food with a varied selection of fresh vegetables and some fruit. Nuts can serve as measured rewards; the right amount depends on species, activity and veterinary advice.',space='Large species need substantial accommodation, strong perches and plenty of safe exercise space. Choose durable enrichment designed for a powerful beak.',noise='Large macaws can produce very loud calls. Consider neighbours and the whole household before choosing one.',fit='Owners with the space, time and resources to meet a large parrot’s daily needs.',examples='Blue-and-gold, scarlet, green-winged and Hahn’s macaws'),
dict(slug='cockatoos',name='Cockatoos',tag='A crest full of character.',example='Cockatoo',life='Several decades',lifetext='Lifespan differs markedly between cockatoo species. Published averages and longevity records are not the same thing. These birds require a multi-decade care plan rather than reliance on a single maximum age.',temperament='Often highly expressive and socially demanding. Build healthy independence with foraging and a steady routine as well as time together.',diet='A balanced feeding plan should include suitable formulated food and fresh produce. Keep energy-rich treats measured and review weight and diet with an avian vet.',space='Provide a robust enclosure, safe exercise, appropriate chew materials and regular enrichment. Feather dust is an important consideration when planning the home environment.',noise='Many species have powerful calls. Noise and feather dust can make some homes unsuitable.',fit='A well-prepared household that understands the group’s social demands, noise and long-term needs.',examples='Umbrella, sulphur-crested and Moluccan cockatoos; galahs'),
dict(slug='amazons',name='Amazons',tag='Vibrant greens. Individual spirits.',example='Amazon parrot',life='Often several decades',lifetext='Amazon parrots can be long-lived, but published figures differ between species and populations. Confirm the species and age, and plan for a long-term relationship with ongoing veterinary care.',temperament='Often animated and confident. Body language matters, and behaviour can change with maturity and breeding condition. Individual temperament should guide any match.',diet='Provide suitable formulated food and fresh produce, with measured seeds and nuts rather than a seed-only diet. Balance calorie intake with activity and monitor body condition.',space='Make room for climbing, exercise and robust enrichment. Provide varied perches and opportunities to search for food.',noise='Calls can be loud. Talking ability varies and should never be promised.',fit='Owners willing to learn parrot body language and support exercise, nutrition and consistent routines.',examples='Blue-fronted, yellow-naped and double yellow-headed Amazons'),
dict(slug='conures',name='Conures',tag='Small in stature. Full of personality.',example='Conure',life='Around 20–35 years',lifetext='VCA gives a broad average of 20–35 years for conures. Individual species and birds vary, so this is general guidance rather than a guarantee or an exact estimate for every conure.',temperament='Often active and inquisitive, with a strong interest in exploration. Social preferences and handling tolerance vary by bird.',diet='Suitable pellets and varied fresh produce support balanced nutrition. Avoid relying on seed and nut mixes as the main diet; discuss gradual dietary changes with an avian vet.',space='Allow room for movement and supervised exercise. Choose appropriate bar spacing and small-parrot-safe toys without hazardous loose parts.',noise='Some conures have piercing calls. A smaller body does not mean a quiet companion.',fit='Households ready for an active small parrot with daily enrichment and social interaction.',examples='Green-cheeked, sun and jenday conures'),
dict(slug='caiques',name='Caiques',tag='Curiosity with a playful streak.',example='Caique',life='A multi-decade commitment',lifetext='Caiques are long-term companions. Published husbandry references give differing estimates, with some citing approximately 30–40 years. Treat this as planning guidance, not a promised lifespan.',temperament='Often energetic and exploratory. Give them opportunities to climb, investigate and engage with suitable enrichment while respecting each bird’s boundaries.',diet='Offer a varied, balanced diet with suitable formulated food and fresh produce. Use treats sparingly and keep an eye on body condition.',space='Provide climbing opportunities, safe foot toys and supervised play. Introductions to other birds should be careful and closely managed.',noise='Calls and vocal activity vary. They should not be selected on the assumption that they will be quiet.',fit='People who can offer structured activity and supervise an energetic bird’s exploration.',examples='Black-headed and white-bellied caiques'),
dict(slug='eclectus',name='Eclectus',tag='Two striking palettes. One remarkable group.',example='Eclectus parrot',life='Around 23–30 years in published records',lifetext='Animal Diversity Web describes captive life expectations around 23–28 years and an average around 30. Older individuals are reported elsewhere, but exceptional longevity is not a typical-life guarantee.',temperament='Attentive birds with individual preferences for interaction. Avoid assuming that every bird has the same temperament based on sex or appearance.',diet='Discuss an Eclectus-specific nutrition plan with an avian vet, including appropriate fresh produce and formulated food. Avoid routine supplements without professional advice.',space='Provide a roomy enclosure, safe exercise and opportunities to forage. A calm-looking bird still needs movement and mental stimulation.',noise='Eclectus can produce loud calls. Individual vocal patterns and response to household activity vary.',fit='Owners who will pay close attention to diet, daily routine and individual behaviour.',examples='Eclectus species from New Guinea, nearby islands and north-eastern Australia'),
dict(slug='parakeets-small-psittacines',name='Parakeets & small psittacines',tag='Little feathers. Plenty to discover.',example='Budgerigar',life='Species-dependent',lifetext='This category spans very different birds. Published examples include around 7–12 years for budgerigars and 25–30 years for Indian ringnecks. Choose the exact species before planning its lifetime care.',temperament='Social, active birds with preferences that vary by species and individual. Small size does not remove the need for companionship, enrichment and gentle handling.',diet='Small parrots need a species-appropriate balance of formulated food, fresh vegetables, some fruit and suitable seeds where appropriate. A seed-only diet is not a balanced plan.',space='Prioritise usable flight space, safe bar spacing and suitable perch diameters. Small birds also need opportunities to exercise and investigate.',noise='Budgies may chatter frequently; other parakeets can have much louder calls. Research the exact species.',fit='Owners looking for a smaller bird while still preparing for meaningful daily care.',examples='Budgerigars, ringnecks, lovebirds, parrotlets and other small parrots')
]
from breeder_content import DISPLAY_NAMES, AFRICAN_GREY_GUIDE
for item in data:
 item['name']=DISPLAY_NAMES[item['slug']]
 if item['slug']=='african-parrots':item.update(AFRICAN_GREY_GUIDE)
def esc(v):return html.escape(str(v),quote=True)
home=(out/'index.html').read_text()
header=re.search(r'<header>.*?</header>',home,re.S).group().replace('href="#"','href="/"').replace('href="#','href="/#')
footer=re.search(r'<footer\b[^>]*>.*?</footer>',home,re.S).group().replace('href="#"','href="/"').replace('href="#','href="/#')
head=re.search(r'<head>.*?</head>',home,re.S).group().replace('href="style.css"','href="/style.css"')
cards=[]
for i,d in enumerate(data):
 cards.append(f'<a class="species-card visual-card" href="/parrots/{d["slug"]}/"><div class="card-photo" data-photo-group="{d["slug"]}"></div><div class="card-copy"><h3>{esc(d["name"])}</h3><p>{esc(d["tag"])}</p><span class="card-link">Discover this group</span></div></a>')
 p=out/'parrots'/d['slug'];p.mkdir(parents=True,exist_ok=True)
 title=f'{d["name"]}: Lifespan, Diet & Care | Crownwing Parrots'
 pagehead=re.sub(r'<title>.*?</title>',f'<title>{esc(title)}</title>',head)
 pagehead=re.sub(r'<meta name="description" content="[^"]*">',f'<meta name="description" content="Explore {esc(d["name"])} with guidance on lifespan, diet, personality, housing and daily care.">',pagehead)
 gallery='<div class="gallery-slots">'+''.join(f'<div class="photo-slot"><span>0{j}</span><p>More photos coming soon</p></div>' for j in range(2,5))+'</div>'
 facts=''.join(f'<div><span>{label}</span><strong>{esc(value)}</strong></div>' for label,value in [('Lifespan',d['life']),('Daily needs','Interaction & enrichment'),('Availability','Enquire directly')])
 sections=''.join(f'<article id="{ident}"><p class="eyebrow">{num}</p><h2>{heading}</h2><p>{esc(d[key])}</p></article>' for num,ident,heading,key in [('01','lifespan','Lifespan & long-term planning','lifetext'),('02','diet','Diet & nutrition','diet'),('03','temperament','Personality & temperament','temperament'),('04','housing','Housing & enrichment','space'),('05','noise','Noise & vocalisation','noise'),('06','suitability','Is this group right for you?','fit')])
 related=''.join(f'<a href="/parrots/{g["slug"]}/">{esc(g["name"])}</a>' for g in data if g['slug']!=d['slug'])
 source_extra='<a href="https://vcahospitals.com/know-your-pet/conures-general">VCA: conures</a>' if d['slug']=='conures' else '<a href="https://animaldiversity.org/accounts/Eclectus_roratus/">Animal Diversity Web: Eclectus</a>' if d['slug']=='eclectus' else ''
 main=f'''<main class="detail-page"><div class="detail-top"><a href="/#parrots">All parrots</a><span>/ {esc(d['name'])}</span></div><section class="detail-intro"><div><p class="eyebrow">THE CROWNWING COLLECTION</p><h1>{esc(d['name'])}</h1><p class="detail-tag">{esc(d['tag'])}</p><p>Explore their character, understand their needs, and discover what a thoughtful beginning looks like.</p><a class="button" href="/?species={d['slug']}#enquire">Enquire about {esc(d['name'])}</a></div><div class="detail-gallery" data-photo-group="{d['slug']}"><div class="gallery-main"></div>{gallery}<p class="gallery-note">Representative species photography; not an individual bird offered for sale.</p></div></section><div class="quick-facts">{facts}</div><div class="detail-body"><aside><p class="eyebrow">IN THIS GUIDE</p><a href="#lifespan">Lifespan</a><a href="#diet">Diet & nutrition</a><a href="#temperament">Personality</a><a href="#housing">Housing & enrichment</a><a href="#noise">Noise</a><a href="#suitability">The right match</a></aside><div class="detail-content"><p class="group-note">This is a species-group guide. Individual needs vary. Examples include: {esc(d['examples'])}.</p>{sections}<div class="guide-sources"><h3>Further reading</h3><a href="https://www.rspca.org.uk/adviceandwelfare/pets/birds/diet">RSPCA: feeding parrots</a><a href="https://www.ivis.org/library/avian-health-and-disease/lifespan-and-longevity">IVIS: lifespan and longevity</a>{source_extra}<p>Lifespan estimates differ between studies and species. Use this guide as a starting point and discuss the individual bird’s diet and care with an avian vet.</p></div></div></div><section class="detail-cta"><div><p class="eyebrow">A THOUGHTFUL NEXT STEP</p><h2>Could {esc(d['name'].lower())} be your match?</h2><p>Tell us about your home, experience and routine.</p></div><a class="button lime" href="/?species={d['slug']}#enquire">Prepare an enquiry</a></section><section class="related"><h2>Explore more parrots</h2><div>{related}</div></section></main>'''
 (p/'index.html').write_text('<!doctype html><html lang="en-GB">'+pagehead+'<body>'+header+main+footer+'<script src="/detail.js"></script></body></html>')
home=re.sub(r'<div class="species-grid" id="species-grid">.*?(?=<p class="caption">)', '<div class="species-grid" id="species-grid">'+''.join(cards)+'</div>',home,flags=re.S)
home=re.sub(r'<dialog id="species-dialog">.*?</dialog>','',home,flags=re.S)
(out/'index.html').write_text(home)
(root/'tools/species-data.json').write_text(json.dumps(data,indent=2))
tail=original[original.index('const menu='):]
slugs=[d['slug'] for d in data]
names=[d['name'] for d in data]
new=f'const speciesSlugs={json.dumps(slugs)},speciesNames={json.dumps(names)};const select=document.getElementById("species-select");speciesNames.forEach(n=>select.add(new Option(n,n)));const picked=speciesSlugs.indexOf(new URLSearchParams(location.search).get("species"));if(picked>=0)select.value=speciesNames[picked];\n'+tail
(out/'app.js').write_text(new)
print('Generated eight species pages and eight photographic cards.')

import subprocess, sys
subprocess.run([sys.executable, str(root/'tools/populate-photos.py')], check=True)
subprocess.run([sys.executable, str(root/'tools/apply-breeder-positioning.py')], check=True)
