from pathlib import Path
import runpy,re,json,html
from urllib.parse import quote
g=runpy.run_path(str(Path(__file__).with_name('expand-site.py')))
globals().update({k:g[k] for k in ['root','out','origin','data','a','blocks','faqs','related','page','photo','linkcards','sales']})
cities=[
('london','London','England','Planning for shared walls and limited space',[
('Look at usable space, not just cage dimensions','If your London home has shared walls or limited floor space, sketch the actual enclosure and exercise area before choosing a bird. Include door clearance, cleaning access and room for supervised movement. A cage that fits a corner may still leave too little usable space for the species you prefer.'),
('Discuss vocalisation with the whole household','Think about neighbours, people working from home and quiet periods. Ask what the individual bird sounds like across a normal day. An African grey’s reputation for speech or a conure’s smaller size does not establish suitability for a flat. Review macaws and cockatoos particularly carefully if sound carries between homes.'),
('Plan care around days away from home','Before sending an enquiry, note your typical time away and who can help when plans change. A predictable care arrangement is more useful than a promise that the bird will always be with you. Include the available space and daily routine in your London enquiry.')]),
('manchester','Manchester','England','Making a working-week care plan',[
('Write down a normal working week','For a Manchester household comparing parrots, a useful first step is to map feeding, cleaning, interaction and exercise around your actual working hours. Include early starts, evenings and days when plans run late. Care should remain workable throughout the week, not only when you have free time.'),
('Agree how household responsibilities are shared','If more than one person will provide care, discuss who handles each task and how information is recorded. The bird’s routine should not depend on one person remembering every detail. Ask about the individual’s response to different people rather than assuming it will accept all handlers immediately.'),
('Compare activity needs before size','Look at conures, caiques and larger parrots in terms of practical enrichment and supervised activity. A smaller bird is not automatically the easiest match for a busy routine. Use your enquiry to describe what you can reliably offer every day.')]),
('birmingham','Birmingham','England','Choosing with the whole household',[
('Make the decision together','If your Birmingham home is shared with family or housemates, discuss noise, cleaning and daily care before anyone selects a favourite bird. List concerns and responsibilities openly. A bird becomes part of the household environment even when only one person considers themselves its owner.'),
('Discuss handling expectations','Ask how the individual reacts to familiar and unfamiliar people and what interaction it prefers. Avoid assuming that a bird described as friendly is suitable for every person. Children need appropriate adult supervision, and the bird must have space to withdraw from unwanted attention.'),
('Prepare clear boundaries for pets and visitors','Think about how doors, other animals and visiting people will be managed. Separate safe spaces and agreed routines help turn a hopeful purchase into a practical plan. Mention existing animals and who will provide care in your Birmingham enquiry.')]),
('leeds','Leeds','England','Assessing the cost of a long-term companion',[
('Build a budget before asking about price','When considering a parrot for a Leeds home, separate the individual bird’s price from the cost of suitable accommodation and ongoing care. Make room for food, safe enrichment, cleaning supplies and replacement equipment. Ask local veterinary providers for relevant costs rather than relying on national averages.'),
('Choose equipment for the exact species','A budgerigar, caique and large macaw need different equipment. Confirm adult size, usable enclosure space and safe bar spacing before buying supplies. An inexpensive setup that needs replacing immediately can cost more than choosing suitable equipment at the start.'),
('Think beyond the first year','Discuss care during holidays, changes in work and unexpected expenses. If your preferred bird may be a companion for decades, identify how your household would manage future changes. Include your care plan, not just a price limit, when enquiring from Leeds.')]),
('bristol','Bristol','England','Preparing a safe exercise area',[
('Review the whole room','Before selecting a bird for your Bristol home, identify a safe area for supervised activity. Check doors, windows, electrical cords and how other animals will be kept separate. Think about where the bird can climb and explore without entering food-preparation areas or other unsuitable spaces.'),
('Choose a species you can accommodate','Review adult size and exercise needs alongside appearance. Large macaws call for substantial usable space and robust equipment. Smaller parrots still need movement and enrichment; they should not be chosen simply because an enclosure takes up less room.'),
('Make everyday safety repeatable','Agree the steps followed before opening the enclosure. Keep the routine simple enough that everyone providing care can follow it. Ask about the individual’s flight and handling history, and explain your planned exercise area in your Bristol enquiry.')]),
('liverpool','Liverpool','England','Asking better questions about the individual bird',[
('Start with identity and history','When looking for parrots for a Liverpool home, request the exact species, known age and available background information. Ask which details are documented and which are uncertain. A species photograph or a broad label such as young parrot cannot replace the history of the individual.'),
('Request useful photographs and video','Ask for recent images or video of the actual bird and context about its routine. A short clip does not establish all-day behaviour or health. Use the visual information alongside records, questions and any agreed viewing opportunity.'),
('Record the feeding and handling routine','Find out what the bird reliably eats, how it communicates discomfort and which interaction it enjoys. These details help you prepare the transition. Include the questions you still need answered in your Liverpool enquiry rather than focusing only on availability.')]),
('sheffield','Sheffield','England','Designing daily enrichment',[
('Plan activities, not only accessories','For a Sheffield home, consider how the bird will spend time when you are not directly interacting. Appropriate foraging, chewing and climbing opportunities should be part of a usable environment. A full cage of toys is not necessarily meaningful enrichment.'),
('Match materials to the bird','Ask which enrichment the individual already uses and choose items appropriate to its size and beak strength. An energetic caique and a large macaw can need different arrangements. Inspect items and remove damaged or unsafe equipment as part of ordinary care.'),
('Observe preferences and adapt','Introduce new activities thoughtfully and record what the bird engages with. Some individuals need time to become comfortable with unfamiliar objects. Tell us how you plan to provide daily enrichment when enquiring from Sheffield.')]),
('nottingham','Nottingham','England','Preparing for a first parrot',[
('Be precise about your experience','If this would be your first parrot in Nottingham, explain what experience you have with birds and what you are still learning. There is no universally best beginner parrot. Suitability depends on the species, the individual and the time, space and support you can offer.'),
('Avoid choosing on speech or affection alone','A bird may never talk, may be vocal at inconvenient times, or may not enjoy the handling you imagined. Choose only if you are comfortable meeting its needs without those hoped-for behaviours. Read the personality and noise sections in the species guides before shortlisting.'),
('Prepare help before the bird arrives','Identify an avian vet and someone suitable to assist if your routine changes. Have the enclosure and known diet ready before a handover. Mention that this is your first bird and list your practical questions in your Nottingham enquiry.')]),
('newcastle','Newcastle upon Tyne','England','Organising enquiries and proposed handover',[
('Confirm the individual before planning travel','If you are enquiring from Newcastle upon Tyne, establish which bird is being discussed before making any journey. Request current details and ask what viewing arrangements, if any, can be agreed. Do not assume a local branch, collection point or delivery route exists.'),
('Resolve the terms clearly','Ask about the price, what is included and any proposed deposit or other terms. Keep a copy of agreed information. Clarify which records and care details will accompany the bird so that important questions do not wait until the day of handover.'),
('Prepare suitable transport arrangements','Discuss the proposed handover and appropriate travel equipment with the relevant keeper and, where needed, an avian professional. Availability and transport arrangements must be confirmed for the individual enquiry. Include Newcastle upon Tyne and any practical travel limitations in your message.')]),
('cardiff','Cardiff','Wales','Making an informed species shortlist',[
('Compare the right things','For a Cardiff household, start with the available space, normal daily routine and tolerance for noise. Then compare species rather than picking solely by colour. Read lifespan, diet, personality and housing information together so the shortlist reflects the whole care commitment.'),
('Understand broad category names','African parrots include birds with different sizes and needs. Parakeets and small psittacines are an even broader category. Ask which exact species is being discussed before making equipment or companionship decisions.'),
('Ask about the match, not only stock','Describe the household you can provide and ask what is known about the individual bird. Availability alone does not make a bird suitable. Include your shortlist and the reasoning behind it in your Cardiff enquiry.')]),
('edinburgh','Edinburgh','Scotland','Planning for future household changes',[
('Look beyond your current routine','Before choosing a parrot for an Edinburgh home, consider possible moves, work changes and time away over the coming years. Several groups can be long-term companions. A workable plan needs room for ordinary life changes rather than assuming today’s arrangements will remain fixed.'),
('Identify backup care','Discuss who could provide care when you are unavailable and how they would learn the bird’s diet and routine. A named helper is only useful if the arrangement is realistic. Keep feeding, veterinary and handling information somewhere it can be passed on.'),
('Match commitment to the actual species','Do not give every parrot the same assumed lifespan. Read the exact species information and ask about known age. Share how you plan to provide ongoing care when preparing your Edinburgh enquiry.')]),
('glasgow','Glasgow','Scotland','Understanding diet before changing it',[
('Ask what is actually eaten','When considering a bird for a Glasgow home, request its current feeding routine and the foods it consistently eats. A list of everything offered can hide selective feeding. This information helps you prepare the first days and avoid unnecessary disruption.'),
('Make species-specific choices','Diet planning differs between birds and depends on age, activity and health. Eclectus parrots merit a specific nutrition conversation; smaller birds also require a balanced plan. Discuss appropriate food and any supplements with an avian vet rather than applying a generic menu.'),
('Plan a careful transition','Ask how to maintain the established diet during a move and when to review it professionally. Do not assume a bird will automatically eat unfamiliar replacement food. Include dietary questions and the species that interests you in your Glasgow enquiry.')]),
('belfast','Belfast','Northern Ireland','Clarifying location and proposed arrangements',[
('Describe where the bird would live','If you are enquiring from Belfast, include the location and practical care setup in your initial message. Availability, viewing and handover arrangements need to be discussed directly. This page does not promise a local branch or a transport service.'),
('Confirm requirements before proceeding','Any proposed arrangement should be checked for the individual bird, origin and destination. Ask what relevant records are available and confirm any applicable requirements through appropriate official sources. Avoid assuming that one previous transaction establishes the terms of another.'),
('Keep care preparation independent of the purchase','You can research species, prepare accommodation and identify suitable veterinary support while clarifying arrangements. Decide what home you can provide before committing to a particular bird. Include your questions about the proposed handover in your Belfast enquiry.')])]

def local_form(city):
 return f'''<section class="contact-layout city-enquiry"><div><p class="eyebrow">YOUR {html.escape(city.upper())} ENQUIRY</p><h2>Prepare a local enquiry</h2><p>Include the species that interests you and the home you can offer. Availability and any proposed travel, viewing or handover arrangements need direct confirmation.</p><p>This creates a downloadable copy. It is not sent or stored.</p></div><div class="contact-form-panel"><form class="local-enquiry-form" data-city="{html.escape(city,quote=True)}"><label>Your name<input name="name" required autocomplete="name"></label><label>Email address<input name="email" type="email" required autocomplete="email"></label><label>Species or group<select name="species"><option>I would like guidance</option>{''.join('<option>'+html.escape(d['name'])+'</option>' for d in data)}</select></label><label>Your home and questions<textarea name="message" required rows="4" placeholder="Your routine, experience, available space and questions…"></textarea></label><button class="button lime">Download my enquiry</button><p class="local-form-status" role="status"></p></form></div></section>'''
local_links=[]
for slug,city,country,focus,sections in cities:
 path='/locations/'+slug+'/';local_links.append((path,city))
 content='<div class="location-note"><strong>Location enquiry guide</strong><p>This page is for people researching parrots in '+city+'. It does not identify a Crownwing branch or confirm local stock, delivery or collection.</p></div>'
 content+=blocks([(focus,'<p>'+sections[0][1]+'</p>')]+[(heading,'<p>'+text+'</p>') for heading,text in sections[1:]])
 content+=blocks([('Research the groups before enquiring','<p>Use the '+a('/parrots/','species collection')+' to compare all eight groups, from African parrots and macaws to conures and small psittacines. Each profile covers diet, lifespan, personality, accommodation and vocalisation. The '+a('/parrots-for-sale/','UK buying enquiry hub')+' explains what to ask about an actual bird.</p><p>Work through the '+a('/guides/buying-a-parrot-checklist/','buying checklist')+' and '+a('/parrot-prices-uk/','price and lifetime cost guidance')+' before agreeing to a purchase. Current availability and any proposed arrangements must be confirmed directly.</p>')])
 content+=local_form(city)+related([('/locations/','All UK city guides'),('/parrots/','Compare species'),('/parrots-for-sale/','Commercial enquiries'),('/guides/preparing-for-a-parrot/','Prepare the home')])
 page(path,'Parrots in '+city+' | Buying enquiries','Researching parrots for sale in '+city+'? Explore '+focus.lower()+', compare species and prepare a location-specific enquiry.','UK LOCATION GUIDES', 'Parrots for '+city+' homes',focus+'. Start with the practical questions, then enquire about the individual bird.',content)
 p=out/path.strip('/')/'index.html';s=p.read_text().replace('</body>','<script src="/local-enquiry.js"></script></body>');p.write_text(s)

page('/locations/','UK parrot city guides | Local buying enquiries','Browse Crownwing’s UK city enquiry guides for London, Manchester, Birmingham, Cardiff, Edinburgh, Glasgow, Belfast and more.','UK CITY ENQUIRY GUIDES','Your city.<br>Your home.<br>A considered choice.','Browse local enquiry guides alongside species and buying information. Confirm availability and practical arrangements directly.',blocks([('What these location pages cover','<p>These guides help you prepare an enquiry from your city and consider the practical home you can provide. They connect to the same species collection and buying information, with a different ownership planning focus on each page.</p><p>A location guide is not a claim of a local branch, local inventory or an established delivery service. Business premises and any service coverage will be added when confirmed. Choose your city below to explore the guide and prepare a downloadable enquiry.</p>')])+linkcards(local_links)+related([('/parrots-for-sale/','UK buying enquiries'),('/parrots/','Parrot collection'),('/parrot-care/','Care guides')]))

commercial=[
('/parrots-for-sale/talking-parrots/','Talking parrots UK','Considering a talking parrot?','Speech is a possibility, not a promise. Choose a bird whose everyday needs you can support.',[
('A talking reputation is not an individual guarantee','<p>People often search for talking parrots when exploring African greys, Amazons or other companions. Vocal learning varies between individuals and environments. A bird associated with a talking species may not develop speech, and an existing vocabulary may not be used in a new home.</p><p>The important test is whether you would still want to care for the bird if it never spoke. Use the '+a('/parrots/african-parrots/','African parrot guide')+' and '+a('/parrots/amazons/','Amazon guide')+' to consider routine, diet, exercise and noise alongside vocal interest.</p>'),
('Ask about actual behaviour','<p>If an individual bird is described as talking, ask what has been observed and in which setting. Request context about its normal vocalisation rather than treating a short recording as proof of what it will do all day. Talking ability should not replace questions about age, history, handling and current care.</p><p>Remember that speech and other calls can coexist. A bird that learns words can also make loud natural sounds. Discuss noise tolerance with everyone sharing the household.</p>'),
('Make a suitable match first','<p>Compare the '+a('/parrots-for-sale/african-grey-parrots/','African grey buying questions')+' and '+a('/parrots-for-sale/amazon-parrots/','Amazon buying questions')+' before deciding on a species. Do not assume that a small bird is incapable of vocal learning or that a large bird will speak.</p><p>When enquiring, include your routine, experience and available space. Ask about the individual’s needs and vocal behaviour without requesting a guaranteed future skill.</p>')]),
('/parrots-for-sale/small-parrots/','Small parrots UK','Small birds.<br>Meaningful commitments.','Compare smaller parrots by species, personality and care needs—not size alone.',[
('Choose an exact species','<p>Small parrot searches can include budgerigars, lovebirds, parrotlets, conures and other birds with different needs. A broad size category does not tell you enough about noise, companionship, lifespan or suitable housing.</p><p>Begin with the '+a('/parrots/parakeets-small-psittacines/','parakeet and small psittacine profile')+' and '+a('/parrots/conures/','conure profile')+'. Identify the exact species before selecting equipment or planning a social arrangement.</p>'),
('Prepare usable accommodation','<p>A small bird still needs room to move, exercise and investigate. Compare safe bar spacing, internal layout and suitable perches, not only the footprint of the enclosure. Make a plan for supervised activity and species-appropriate enrichment.</p><p>Read the '+a('/guides/parrot-housing-enrichment/','housing and enrichment guide')+' and consider how the bird’s routine will fit a normal working week.</p>'),
('Ask practical buying questions','<p>Request the bird’s known age, established diet and social background. If you already keep birds, discuss separate housing and obtain appropriate advice before introductions. Do not assume every small bird is quiet, suitable for children or easy to handle.</p><p>Use the '+a('/parrots-for-sale/parakeets-small-parrots/','small parrot buying enquiry page')+' or '+a('/parrots-for-sale/conures/','conure enquiry page')+' to prepare questions about the individual, current availability and proposed arrangements.</p>')]),
('/parrots-for-sale/large-parrots/','Large parrots UK','A remarkable presence.<br>A substantial care plan.','Research macaws, cockatoos and other larger parrots around usable space, noise and long-term care.',[
('Think in practical terms','<p>A large parrot can be visually striking, but choosing one should begin with the household environment. Consider room for exercise, suitable accommodation, durable equipment and a sustainable daily routine. Powerful beaks and loud vocalisation deserve attention before a buying enquiry.</p><p>Explore the '+a('/parrots/macaws/','macaw profile')+' and '+a('/parrots/cockatoos/','cockatoo profile')+' as different groups rather than one interchangeable category.</p>'),
('Plan for long-term care','<p>Some larger parrots can remain companions for decades. Think about future household changes and who could provide care if you were unavailable. Review ongoing food, equipment and veterinary costs as well as the price of the bird.</p><p>The '+a('/parrot-prices-uk/','parrot price planning page')+' helps separate the purchase from lifetime costs. Actual prices must be confirmed for the individual.</p>'),
('Discuss the individual and the home','<p>Ask about background, current diet, handling preferences and response to unfamiliar people. Describe the space available and the experience of everyone involved in care. Size alone does not tell you the bird’s temperament.</p><p>Use the '+a('/parrots-for-sale/macaws/','macaw buying enquiry page')+' or '+a('/parrots-for-sale/cockatoos/','cockatoo buying enquiry page')+' for the questions to resolve before committing.</p>')]),
('/parrot-prices-uk/','Parrot prices UK | Purchase & care costs','Understand the price.<br>Plan the commitment.','Ask for an individual quotation and compare it with the actual cost of suitable care.',[
('There is no single UK parrot price','<p>A useful price comparison starts with the exact species and individual bird. Age, known background and what is included can affect a proposed price, while accommodation and ongoing care form a separate budget. This website does not publish unconfirmed price ranges.</p><p>Ask for a clear quotation identifying the bird, the proposed terms and anything included. Read the '+a('/guides/buying-a-parrot-checklist/','buying checklist')+' before agreeing to a deposit or payment.</p>'),
('Understand what is included','<p>Confirm whether any equipment, care information or records accompany the bird. Do not infer that an enclosure is suitable simply because it is offered alongside a purchase. Viewing, collection and any proposed transport arrangements should be clarified directly.</p><p>A quoted price is only useful when the individual and the terms are understood. Keep a record of the information agreed.</p>'),
('Budget beyond the purchase','<p>Allow for suitable housing, food, safe enrichment, cleaning and veterinary support. Ask providers relevant to your location about costs rather than treating a national estimate as a personal budget. Replacement equipment and care while you are away should also be considered.</p><p>Use the '+a('/guides/parrot-ownership-costs/','ownership costs guide')+' and the '+a('/locations/','city enquiry guides')+' to prepare a practical plan, then ask about the species and individual that interest you.</p>')])]
extra_links=[]
for path,title,h1,intro,sections in commercial:
 extra_links.append((path,title))
 page(path,title+' | Buying enquiries',intro,'UK COMMERCIAL GUIDES',h1,intro,blocks(sections)+faqs([('Are prices or individual birds listed here?','No. Current birds and prices require direct confirmation. These pages help you research the care commitment and prepare a useful enquiry.'),('Can I enquire from my city?','Use the UK city guide hub to prepare a location-specific downloadable enquiry. It does not confirm a local branch or delivery service.')])+related([('/parrots-for-sale/','All species buying pages'),('/locations/','UK city guides'),('/contact/','Prepare an enquiry'),('/parrot-care/','Care library')]))

# Surface the new hierarchy on core pages; do not leave location pages orphaned.
for route in ['parrots-for-sale','parrots','']:
 p=out/route/'index.html';s=p.read_text()
 more='<section class="section commercial-directory"><p class="eyebrow">EXPLORE YOUR NEXT STEP</p><h2>Buying questions.<br>Local preparation.</h2>'+linkcards(extra_links+[('/locations/','UK city enquiry guides')])+'</section>'
 s=s.replace('</main>',more+'</main>');p.write_text(s)
for p in out.rglob('index.html'):
 s=p.read_text().replace('<a href="/contact/">Contact & enquiries</a>','<a href="/locations/">UK city guides</a><a href="/parrot-prices-uk/">Parrot prices & costs</a><a href="/contact/">Contact & enquiries</a>')
 p.write_text(s)

# Metadata for all routes, with city drafts held out of search until real local service facts exist.
paths=[];public_paths=[]
for p in sorted(out.rglob('index.html')):
 rel=p.parent.relative_to(out).as_posix();path='/' if rel=='.' else '/'+rel+'/'
 paths.append(path);s=p.read_text();s=re.sub(r'<link rel="canonical"[^>]*>','',s);s=re.sub(r'<script type="application/ld\+json">.*?</script>','',s,flags=re.S)
 title=html.unescape(re.search(r'<title>(.*?)</title>',s).group(1))
 schema={'@context':'https://schema.org','@type':'WebPage','name':title,'url':origin+path,'isPartOf':{'@type':'WebSite','name':'Crownwing Parrots','url':origin+'/'}}
 if path!='/':
  crumbs=[{'@type':'ListItem','position':1,'name':'Home','item':origin+'/'}]
  if path.startswith('/locations/') and path!='/locations/':crumbs.append({'@type':'ListItem','position':2,'name':'UK city guides','item':origin+'/locations/'})
  elif path.startswith('/parrots-for-sale/') and path!='/parrots-for-sale/':crumbs.append({'@type':'ListItem','position':2,'name':'UK buying enquiries','item':origin+'/parrots-for-sale/'})
  crumbs.append({'@type':'ListItem','position':len(crumbs)+1,'name':title.split('|')[0].strip(),'item':origin+path});schema['breadcrumb']={'@type':'BreadcrumbList','itemListElement':crumbs}
 robots=''
 if path.startswith('/locations/') and path!='/locations/':robots='<meta name="robots" content="noindex,follow">'
 else:public_paths.append(path)
 s=s.replace('</head>',f'<link rel="canonical" href="{origin+path}">{robots}<script type="application/ld+json">{json.dumps(schema)}</script></head>');p.write_text(s)
from xml.sax.saxutils import escape
def sitemap(routes):return '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+escape(origin+p)+'</loc></url>' for p in routes)+'</urlset>'
(out/'sitemap.xml').write_text(sitemap(public_paths))
(root/'tools/city-page-status.json').write_text(json.dumps({'status':'private review drafts; noindex until local service details are verified','cities':[c[1] for c in cities],'required_before_indexing':['Confirmed service relationship with each location','Genuine city-specific availability or viewing/transport information','Verified business contact details'],'commercial_pages':[p for p,_ in extra_links]},indent=2))
print(f'Built {len(cities)} city guides and {len(commercial)} commercial pages; site total {len(paths)} pages.')

# Apply the current visible-copy preference after regenerating pages.
import runpy as _notice_runner
_notice_runner.run_path(str(root/'tools/clean-visible-notices.py'))
import subprocess, sys
subprocess.run([sys.executable, str(root/'tools/populate-photos.py')], check=True)
subprocess.run([sys.executable, str(root/'tools/apply-breeder-positioning.py')], check=True)
