from pathlib import Path
import re,json,html
from urllib.parse import quote
from site_config import PUBLIC_ORIGIN
root=Path(__file__).resolve().parents[1];out=root/'dist';origin=PUBLIC_ORIGIN
data=json.loads((root/'tools/species-data.json').read_text());home=(root/'tools/templates/home.html').read_text()
e=lambda v:html.escape(str(v),quote=True)
head=re.search(r'<head>.*?</head>',home,re.S).group().replace('href="style.css"','href="/style.css"')
brand='<a href="/" class="brand"><span class="brandmark">♛</span><span>CROWN WING<small>PARROTS</small></span></a>'
header=f'<header>{brand}<nav aria-label="Main navigation"><a href="/parrots/">Our parrots</a><a href="/our-approach/">Our approach</a><a href="/parrot-care/">Parrot care</a><a href="/parrots-for-sale/">Buying a parrot</a></nav><a class="button nav-cta" href="/contact/">Make an enquiry</a><button class="menu" aria-label="Open navigation" aria-expanded="false">☰</button></header>'
footer=f'<footer>{brand}<p>Extraordinary birds. Thoughtful beginnings.</p><div><a href="/parrots-for-sale/">Parrot enquiries UK</a><a href="/our-approach/">Our approach</a><a href="/parrot-care/">Care guides</a><a href="/contact/">Contact & enquiries</a><span>© 2026 Crownwing Parrots</span></div></footer>'
credits=''
def a(path,text):return f'<a href="{path}">{text}</a>'
def blocks(sections):return ''.join(f'<section class="article-section"><h2>{title}</h2>{text}</section>' for title,text in sections)
def faqs(items):return '<div class="page-faq">'+''.join(f'<details><summary>{q}</summary><p>{ans}</p></details>' for q,ans in items)+'</div>'
def related(items):return '<section class="related"><h2>Keep exploring</h2><div>'+''.join(a(*item) for item in items)+'</div></section>'
def cta(title,slug=None):return f'<section class="detail-cta"><div><p class="eyebrow">A THOUGHTFUL NEXT STEP</p><h2>{title}</h2><p>Start with your experience, your home and the birds that interest you.</p></div><a class="button lime" href="/contact/{"?species="+slug if slug else ""}">Prepare an enquiry</a></section>'
def photo(d):
 return f'<figure class="editorial-photo" data-photo-group="{d["slug"]}"><figcaption>Representative species photo. {a("/parrots/"+d["slug"]+"/","Species guide")}</figcaption></figure>'
def page(path,title,desc,kicker,h1,intro,body,side=None):
 h=re.sub(r'<title>.*?</title>',f'<title>{e(title)} | Crownwing Parrots</title>',head)
 h=re.sub(r'<meta name="description" content="[^"]*">',f'<meta name="description" content="{e(desc)}">',h)
 main=f'<main class="content-page"><div class="detail-top">{a("/","Home")}<span>/ {e(h1)}</span></div><section class="page-intro"><div><p class="eyebrow">{kicker}</p><h1>{h1}</h1><p class="page-lead">{intro}</p></div>{side or ""}</section>{body}</main>'
 p=out/path.strip('/')/'index.html';p.parent.mkdir(parents=True,exist_ok=True);p.write_text('<!doctype html><html lang="en-GB">'+h+'<body>'+header+main+footer+credits+'<script src="/common.js"></script></body></html>')
def collection():
 return '<div class="species-grid">'+''.join(f'<a class="species-card visual-card" href="/parrots/{d["slug"]}/"><div class="card-photo" data-photo-group="{d["slug"]}"></div><div class="card-copy"><h3>{e(d["name"])}</h3><p>{e(d["tag"])}</p><span class="card-link">Read the species guide</span></div></a>' for d in data)+'</div>'

approach=blocks([
('The right bird starts with the right questions','<p>Crownwing Parrots brings together eight groups of parrots for people exploring a companion bird in the United Kingdom. Our starting point is simple: a bird’s needs and your household routine should shape the decision. Colour, size and talking ability are interesting, but they are not enough to establish a suitable match.</p><p>We use our '+a('/parrots/','parrot species guides')+' to introduce the differences between African parrots, macaws, cockatoos, Amazons, conures, caiques, Eclectus and smaller psittacines. These are group introductions rather than promises about an individual bird. Species, age, history and temperament all matter.</p>'),
('A conversation about your everyday life','<p>Before choosing a bird, think through a normal working week. Who will provide care? Where will the enclosure sit? How much safe exercise space is available? Will household members and neighbours be comfortable with vocalisation? An enthusiastic first week is not the same as a sustainable routine.</p><p>Existing birds, young children, other animals, rented accommodation and frequent travel can all affect the practical arrangements. Our '+a('/guides/choosing-a-parrot/','guide to choosing a parrot')+' helps you work through these considerations without ranking one species as universally “best”.</p>'),
('Know the individual, not only the species','<p>A photograph tells you very little about a bird’s background. Ask about exact species, age, diet, handling preferences, health history and relevant records. Request recent photographs or video of the individual and ask what information is known, documented or uncertain.</p><p>Descriptions such as “friendly”, “hand-reared” or “talking” need context. Ask how the bird responds to unfamiliar people and what interaction it actually enjoys. A behaviour seen in one setting may not carry over immediately to a new home.</p>'),
('Clear information before a commitment','<p>Current birds, prices, viewing possibilities and handover arrangements must be confirmed directly. The representative photographs used in our collection explain the species; they do not identify a bird currently available to purchase. We do not label a bird as in stock without an actual listing.</p><p>Use the '+a('/parrots-for-sale/','UK parrot buying hub')+' for the questions to resolve before agreeing to a purchase. Enquiries should include the species that interests you, your experience and your practical care plan.</p>'),
('Prepare for life beyond the first day','<p>Set up suitable accommodation, find an avian vet and make a plan for daily cleaning, feeding, enrichment and supervised exercise. Consider the financial commitment as well as the time involved. Some parrots remain companions for decades, so future moves and changes in circumstances deserve attention now.</p><p>Our '+a('/parrot-care/','parrot care hub')+' connects feeding, housing, enrichment and first-week preparation. Educational information helps you ask better questions; it cannot replace assessment of the individual bird by an appropriate professional.</p>')])
page('/our-approach/','Our approach to choosing a parrot','Learn Crownwing’s approach to matching parrots with suitable UK homes, with clear questions about care, history and long-term ownership.','THE CROWNWING APPROACH','A thoughtful beginning.<br>A lasting commitment.','Choose with understanding. Start with the bird’s needs, your home and a realistic plan for the years ahead.',approach+cta('Let’s talk about the right match')+related([('/guides/choosing-a-parrot/','Choosing a parrot'),('/parrots-for-sale/','Buying questions'),('/parrot-care/','Care guides')]),photo(data[0]))

sale_profiles=[
('african-grey-parrots','African grey parrots','African greys reward careful research. Their reputation for intelligence and vocal learning should not overshadow their need for enrichment, security and a stable routine. A grey that is confident with one person may need time to become comfortable with another.','Ask whether the bird is a Congo African grey or Timneh, what its current diet looks like, and how it reacts to new people or changes in its environment. Discuss known health history and any veterinary records.','A person looking for an African grey should think beyond the hope of a talking bird. Speech is never guaranteed. The stronger question is whether you can meet the bird’s needs even if it never says a word.'),
('macaws','Macaws','Buying a macaw begins with the practical reality of size, noise and a powerful beak. Large macaws and smaller species such as Hahn’s macaws should not be treated as interchangeable. The space and equipment appropriate for one may be unsuitable for another.','Confirm the exact species, adult size and enclosure needs. Ask about handling experience, favourite enrichment, existing diet and how the individual uses its beak during interaction.','Before enquiring about a large macaw, consider whether your home has a genuinely usable exercise area. Decorative cage dimensions and a bird’s impressive appearance are less useful than a clear plan for movement and safe daily activity.'),
('cockatoos','Cockatoos','A cockatoo’s expressive crest and engaging behaviour can be appealing, but ownership requires a realistic view of social demands, noise and feather dust. Choosing the right species and understanding the individual bird are essential.','Ask about its daily routine, independent foraging, response to time alone and comfort with handling. Discuss feather dust and whether anyone in the household has relevant sensitivities.','Avoid making affection the only selection criterion. Think about what happens when you leave for work, change your routine or need someone else to provide care. A plan for healthy independence matters alongside time together.'),
('amazon-parrots','Amazon parrots','Amazon parrots are a varied group, with striking markings and individual personalities. Buying one means learning its body language and planning for exercise and appropriate nutrition, not simply choosing a bird with a reputation for talking.','Confirm the species and age. Ask about behaviour around unfamiliar people, known seasonal changes, existing feeding habits and previous veterinary advice about body condition.','An Amazon’s personality may develop as it matures. Discuss the individual’s history and avoid assuming that a young bird’s current behaviour will remain unchanged throughout its life.'),
('conures','Conures','Conures appeal to people seeking a smaller parrot, but small size does not make care effortless. Green-cheeked, sun and jenday conures differ in appearance and vocalisation, while individual temperament remains important.','Ask which species you are considering and what a normal day sounds like. Request information on diet, safe toy preferences, handling and the bird’s interactions with household activity.','If noise is a major concern, discuss it before choosing a conure. A short quiet video is not proof of a quiet bird. Your choice should remain workable during active, vocal parts of the day.'),
('caiques','Caiques','Caiques are often noticed for lively exploration and colourful plumage. Their activity calls for supervised play, suitable enrichment and owners who respect their boundaries rather than expecting constant handling.','Ask about the individual’s activity level, response to new toys and handling preferences. Discuss introductions to existing birds and how separate spaces would be managed.','Plan for climbing and investigating as well as social interaction. An energetic bird needs a safe outlet for its curiosity, and care should not depend on unsupervised access to the household.'),
('eclectus-parrots','Eclectus parrots','Eclectus parrots are visually distinctive, but a sound buying decision starts with nutrition, species identification and individual behaviour. Their care deserves more attention than a simple male-versus-female comparison.','Request the exact species information available, the bird’s current diet and any relevant veterinary advice. Ask how comfortable it is with everyday household activity and unfamiliar people.','Do not change feeding abruptly because a generic online menu sounds attractive. Understand the current routine and arrange an individual nutrition discussion with an avian vet before making substantial changes.'),
('parakeets-small-parrots','Parakeets & small parrots','Budgerigars, ringnecks, lovebirds and parrotlets are different birds with different needs. Buying a small parrot is still a meaningful commitment to suitable accommodation, daily care and species-appropriate companionship.','Start by identifying the exact species. Ask about age, diet, social history, flight opportunities and whether the bird has been kept alone or with others.','Do not use the label “parakeet” as a complete care plan. A budgerigar and an Indian ringneck differ substantially in size, behaviour and life expectancy. Choose the individual species before choosing equipment.')]
sales=[]
for d,(slug,name,opening,ask,consider) in zip(data,sale_profiles):
 path='/parrots-for-sale/'+slug+'/';sales.append((path,name+' enquiries'))
 content=blocks([
 ('Considering '+name.lower()+' for sale in the UK?',f'<p>{opening}</p><p>At Crownwing, this page helps you prepare a useful enquiry about {name.lower()}. It is not a live stock listing: current availability, individual details and prices need direct confirmation. Begin with the {a("/parrots/"+d["slug"]+"/",name.lower()+" species guide")} to understand lifespan, diet and everyday care.</p>'),
 ('What to ask about the individual',f'<p>{ask}</p><p>Request recent photographs or a video of the actual bird rather than relying on representative species images. Ask what background information is supported by records, what is based on observation, and what is not known. Discuss any relevant documentation before making an agreement.</p>'),
 ('A suitable home comes first',f'<p>{consider}</p><p>Use our {a("/guides/choosing-a-parrot/","parrot selection guide")} to assess your routine and our {a("/guides/parrot-housing-enrichment/","housing and enrichment guide")} to prepare the home. Your household’s ability to provide consistent care matters more than a quick purchase.</p>'),
 ('Price, ongoing costs and handover','<p>Ask for the price of the specific bird and a clear explanation of what is included. Compare that with the cost of appropriate accommodation, food, enrichment and veterinary care. A low initial price does not establish value or suitability.</p><p>Confirm viewing arrangements, the information provided at handover and any terms before paying or travelling. Do not assume collection or delivery is available until it has been agreed for the individual enquiry.</p>'),
 ('Prepare a useful enquiry',f'<p>Include the group or species you are interested in, your experience with birds, the space available and your typical daily routine. If you already have parrots, explain how you would manage separate housing and introductions. Add your questions about age, health records, diet and the proposed handover.</p><p>Read {a("/our-approach/","our approach")} for the thinking behind a considered match, then {a("/contact/?species="+d["slug"],"prepare your "+name.lower()+" enquiry")}.</p>')])
 content+=faqs([('Are '+name.lower()+' currently available?','Availability is confirmed directly. The photographs on this website represent species and are not live listings of individual birds.'),('How much does an individual bird cost?','A price should be supplied for the specific bird, together with what is included and the relevant terms. No price is advertised here until those details are confirmed.'),('Can I request more photographs?','Yes—include a request for current photographs or video of the individual in your enquiry. The species pages have four photo positions ready for a fuller gallery.')])+cta('Ask about '+name.lower(),d['slug'])+related([('/parrots/'+d['slug']+'/',name+' care & lifespan'),('/guides/buying-a-parrot-checklist/','Buying checklist'),('/guides/parrot-ownership-costs/','Ownership costs'),('/parrots-for-sale/','All UK parrot enquiries')])
 page(path,name+' for sale UK | Buying enquiries','Considering '+name.lower()+' for sale in the UK? Explore suitability, buying questions, care needs and how to enquire about individual availability.','UK PARROT BUYING ENQUIRIES',name+' for UK homes','Understand the bird. Prepare the home. Ask the right questions before you commit.',content,photo(d))

guide_data=[
('choosing-a-parrot','Choosing a parrot: finding the right fit','Choosing a parrot for your home','A practical starting point for comparing species, routines, noise, space and long-term care.',[
('Start with your routine, not a favourite photograph','<p>Write down what an ordinary week looks like, including work, travel and time away from home. Identify who will provide feeding, cleaning, enrichment and interaction. A sustainable routine should work beyond weekends and the first few weeks.</p><p>Then consider the household. Noise tolerance, usable space, other animals and the expectations of everyone living with the bird can change which species are appropriate. Make these decisions before narrowing the shortlist.</p>'),
('Compare exact species','<p>Group names are helpful for browsing, but they do not describe identical needs. Small and large macaws differ substantially; parakeets include birds with very different adult sizes and lifespans. Use the '+a('/parrots/','parrot collection')+' to explore groups, then ask about the exact species.</p><p>Compare diet, accommodation, vocalisation and long-term commitment together. A smaller bird is not automatically a quiet or low-maintenance bird, and talking ability should not be treated as an essential feature.</p>'),
('Meet the individual through better questions','<p>Ask what the bird enjoys, what makes it uncomfortable and how it reacts to unfamiliar people. Request an explanation of its current routine and the information available about its history. Ask for recent photographs or video and distinguish documented facts from assumptions.</p><p>Behaviour is influenced by environment and experience. A label such as “friendly” cannot guarantee that a bird will immediately behave the same way in your home. Allow room for gradual adjustment.</p>'),
('Build a shortlist you can support','<p>Select two or three possibilities and compare the real daily requirements. Consider what would happen if your working hours changed or you needed someone else to care for the bird. Review '+a('/guides/parrot-ownership-costs/','ongoing ownership costs')+' as well as purchase price.</p><p>Before making a commitment, work through the '+a('/guides/buying-a-parrot-checklist/','buying checklist')+' and '+a('/guides/preparing-for-a-parrot/','home preparation guide')+'. A sensible match should remain practical even when the bird is vocal, independent or uninterested in talking.</p>')]),
('buying-a-parrot-checklist','Buying a parrot in the UK: questions to ask','Your parrot buying checklist','Use specific questions to understand the individual bird and the proposed purchase before agreeing to a handover.',[
('Identify the bird and its background','<p>Ask for the exact species, known age and any identifying information. Find out how long the bird has been with its current keeper and what is known about its earlier history. Do not assume “young”, “baby” or “hand-reared” tells you everything needed to make a decision.</p><p>Ask which details are supported by records. If some information is unknown, have that stated clearly. Request any documentation relevant to the particular species and transaction, and confirm requirements with the appropriate official source where needed.</p>'),
('Understand diet, health and daily care','<p>Request a description of the actual daily feeding routine, including foods the bird reliably eats. Ask about known health issues, previous veterinary examinations and available records. Agree how existing information will be passed on.</p><p>Discuss exercise, sleeping arrangements, cleaning and enrichment. These details help you prepare a stable transition rather than replacing every part of the bird’s routine immediately.</p>'),
('Clarify handling and behaviour','<p>Ask how the individual reacts to familiar and unfamiliar people, how it communicates discomfort and what kinds of interaction it prefers. If you have children, pets or existing birds, discuss those circumstances before choosing.</p><p>Look for context rather than absolute promises. Talking, tameness and sociability vary. A bird that steps onto one person’s hand may still need patience and gradual training with another.</p>'),
('Resolve the terms before paying or travelling','<p>Confirm the specific bird, price, what is included, any proposed deposit and the applicable terms. Verify the person or business you are dealing with and the arrangements for viewing and handover. Ask questions before transferring money.</p><p>Discuss collection or delivery rather than assuming either service is offered. Confirm the care information and records that will accompany the bird. Keep a copy of what has been agreed.</p>'),
('Prepare the home before the handover','<p>Work through '+a('/guides/preparing-for-a-parrot/','home and first-week preparation')+' and identify an avian vet. Check the enclosure, food, safe perches and transport arrangements ahead of time. If you already keep birds, obtain professional advice on separation and health precautions.</p><p>Use '+a('/parrots-for-sale/','Crownwing’s UK buying enquiry pages')+' to explore a particular group, then prepare an enquiry with the questions you still need answered.</p>')]),
('parrot-diet-nutrition','Parrot diet and nutrition | Feeding guide','A balanced diet starts with the right species','Understand the feeding questions to discuss before choosing food or changing your bird’s routine.',[
('Find out what the bird actually eats','<p>Ask for the current feeding routine, not only a list of foods that have been offered. A bird may select favourite items from a mixed bowl and leave the rest. Record the foods, quantities and preparation methods before considering changes.</p><p>Feeding advice should reflect the exact species, age, health and activity level. Our '+a('/parrots/','species guides')+' introduce the groups, but an individual plan belongs in a conversation with an avian vet.</p>'),
('Aim for balanced nutrition','<p>The RSPCA recommends suitable complete pellets alongside varied fresh vegetables and fruit for many parrots. Species with different feeding needs require a tailored approach. An all-seed menu can be nutritionally unbalanced.</p><p>Offer clean water and maintain hygienic feeding equipment. Fresh foods need appropriate handling and removal when spoiled. Food selection should support a workable everyday routine rather than depend on occasional elaborate meals.</p>'),
('Treats and dietary changes','<p>Use seeds and nuts thoughtfully as part of the bird’s overall intake rather than letting rewards replace balanced food. Discuss portion sizes and any supplements with an avian vet.</p><p>Dietary conversion should be planned carefully. Do not simply remove familiar food and assume the bird will eat its replacement. Ask for guidance on monitoring intake and body condition during a change.</p>'),
('Check food safety','<p>Avocado is poisonous to parrots and must not be offered. Check unfamiliar foods with a trusted bird-care source before sharing them. Keep food preparation separate from household items or substances that may be hazardous to birds.</p><p>For further guidance, read the '+a('https://www.rspca.org.uk/adviceandwelfare/pets/birds/diet','RSPCA parrot feeding advice')+'. Return to the '+a('/parrot-care/','care hub')+' for housing, enrichment and home preparation.</p>')]),
('parrot-housing-enrichment','Parrot housing and enrichment | Home guide','A home designed for movement and curiosity','Plan accommodation, safe exercise and daily activities around the individual bird.',[
('Choose usable space','<p>Start with the exact species and adult size. The enclosure must suit the bird’s movement and provide safe spacing between bars. Think about internal layout: food bowls and toys should not fill all the room available for movement.</p><p>Consider where the enclosure will stand, how it will be cleaned and whether the household can offer safe exercise outside it. A beautiful cage is not enough if the practical routine does not work.</p>'),
('Make exercise part of the plan','<p>Prepare an area for supervised activity with doors and windows secured and household hazards addressed. Think through interactions with people, pets and other birds. Choose arrangements that can be followed consistently.</p><p>Do not assume all parrots can share an enclosure. Ask for advice on species-appropriate social arrangements and careful introductions. The '+a('https://www.rspca.org.uk/adviceandwelfare/pets/birds/environment','RSPCA housing guidance')+' offers a useful starting point.</p>'),
('Offer meaningful enrichment','<p>Provide appropriate opportunities to explore, chew, climb and search for food. Choose toys for the individual’s size and beak strength, inspect them regularly and remove damaged or unsafe items.</p><p>Introduce new activities thoughtfully and observe how the bird responds. Enrichment should support normal behaviour, not simply make the enclosure look busy. See the '+a('https://www.rspca.org.uk/adviceandwelfare/pets/birds/enrichment','RSPCA enrichment guidance')+' for ideas.</p>'),
('Keep safety and maintenance practical','<p>Make cleaning, equipment checks and replacement of damaged items part of the routine. Prepare the room as well as the enclosure; safe housing depends on the whole environment.</p><p>Use the '+a('/guides/preparing-for-a-parrot/','preparation checklist')+' to review household hazards, and the '+a('/guides/parrot-ownership-costs/','ownership cost guide')+' to allow for equipment and ongoing replacement.</p>')]),
('preparing-for-a-parrot','Preparing for a new parrot | First-week guide','Before your parrot comes home','Prepare the space, understand the existing routine and leave room for a gradual adjustment.',[
('Set up before the handover','<p>Have suitable accommodation, food, clean water, safe perches and appropriate enrichment ready before bringing the bird home. Check the layout and make sure the care arrangements are understood by everyone involved.</p><p>Ask for the individual bird’s established diet, daily routine and handling preferences. Keep this information accessible so the transition does not depend on remembering a brief conversation at handover.</p>'),
('Review household hazards','<p>Birds can be vulnerable to airborne hazards. Review cookware, aerosols, smoke and other products used around the home. Avoid exposing birds to PTFE-coated cookware fumes, and choose an appropriate location away from household hazards.</p><p>Secure windows, doors and electrical cords. Manage interactions with other animals carefully. Consult '+a('https://vcahospitals.com/lakeline/know-your-pet/household-hazards-and-dangers-to-birds','VCA’s household hazard guidance')+' and ask your avian vet about your particular setup.</p>'),
('Find veterinary support','<p>Identify an avian vet before the bird arrives and establish how to obtain urgent advice if needed. Ask what records to bring and discuss initial assessment, feeding and any precautions around existing birds.</p><p>Health questions are easier to manage with a clear contact and a record of the bird’s background. Do not wait until a concern arises to start searching for appropriate veterinary help.</p>'),
('Allow the first week to be an adjustment','<p>Give the bird time to observe its new surroundings. Avoid expecting immediate handling, speech or affection. Watch how it responds and follow a steady routine informed by the information you received.</p><p>Maintain familiar food while discussing changes with an avian vet. Read the '+a('/guides/parrot-diet-nutrition/','diet guide')+' and '+a('/guides/parrot-housing-enrichment/','housing guide')+' before making major changes.</p>')]),
('parrot-ownership-costs','Parrot ownership costs UK | Planning guide','The real cost is more than the purchase price','Build a realistic budget for accommodation, everyday care and the unexpected.',[
('Separate purchase price from lifetime care','<p>The initial price of a parrot is only one part of ownership. Start by identifying the exact species and suitable equipment rather than comparing birds on price alone. A smaller bird still needs an appropriate environment and veterinary care.</p><p>Request a clear price for the specific individual and an explanation of what is included. Our '+a('/parrots-for-sale/','UK buying enquiry hub')+' explains the information to confirm before proceeding.</p>'),
('Plan the setup budget','<p>Allow for accommodation, appropriate perches, feeding equipment, transport and safe enrichment. Large parrots may require robust equipment and more usable space. Assess the actual products and arrangements needed for your chosen species.</p><p>Do not buy an enclosure solely because it is advertised for parrots. Check size, usable layout, bar spacing and suitability with an informed source. See the '+a('/guides/parrot-housing-enrichment/','housing guide')+' before finalising the setup.</p>'),
('Account for recurring expenses','<p>Budget for food, cleaning supplies, replacement toys and worn equipment. Plan for routine veterinary care and ask local avian practices about their services and costs. Prices vary by location, provider and the bird’s needs, so obtain relevant quotations.</p><p>Also consider care when you travel or cannot follow the usual routine. Identify suitable help and establish its availability rather than treating it as an afterthought.</p>'),
('Leave room for uncertainty','<p>Unexpected health concerns and changes in household circumstances can affect costs. Keep a practical reserve and think about long-term arrangements, particularly for birds that may be companions for decades.</p><p>Money is only part of the commitment. Daily time and consistency matter too. Use the '+a('/guides/choosing-a-parrot/','species selection guide')+' to check whether the financial and practical requirements fit your home.</p>')])]
guidelinks=[]
for slug,title,h1,intro,sections in guide_data:
 path='/guides/'+slug+'/';guidelinks.append((path,h1));page(path,title,intro,'THE CROWNWING CARE LIBRARY',h1,intro,blocks(sections)+related([('/parrot-care/','All care guides'),('/parrots/','Explore species'),('/our-approach/','Our approach'),('/contact/','Prepare an enquiry')]))
def linkcards(items):return '<div class="link-card-grid">'+''.join(f'<a class="link-card" href="{path}"><h3>{text}</h3><span>Explore this page</span></a>' for path,text in items)+'</div>'
page('/parrot-care/','Parrot care guides | Diet, housing & ownership UK','Explore practical parrot care guides covering feeding, housing, enrichment, home preparation, buying questions and ownership costs.','CARE STARTS WITH UNDERSTANDING','Better informed.<br>Better prepared.','Practical reading for the questions that matter before you choose a parrot and prepare its home.',linkcards(guidelinks)+blocks([('Care depends on the species and the individual','<p>There is no single routine that fits every parrot. Begin with the exact species and the individual bird’s background, then use these guides to prepare your questions. Read the '+a('/parrots/','species profiles')+' for group-specific considerations and discuss health or feeding changes with an avian vet.</p>')])+cta('Turn research into a thoughtful enquiry'))
page('/parrots/','Parrot species UK | Explore eight groups','Explore African parrots, macaws, cockatoos, Amazons, conures, caiques, Eclectus and parakeets. Compare lifespan, diet and daily care.','THE CROWNWING COLLECTION','Find your fascination.','Explore the character and care of eight parrot groups. Start with the species; make the final choice around the individual.',collection()+blocks([('From species research to a sensible decision','<p>Each group guide introduces lifespan, diet, personality, housing, vocalisation and suitability. Use this collection alongside our '+a('/guides/choosing-a-parrot/','selection guide')+' rather than treating appearance as the only consideration.</p><p>When you are ready to discuss a particular bird, the '+a('/parrots-for-sale/','UK buying hub')+' explains availability enquiries, price questions and the information to request before making a commitment.</p>')])+related([('/parrots-for-sale/','Buying enquiries'),('/parrot-care/','Care library'),('/our-approach/','Our approach')]))
page('/parrots-for-sale/','Parrots for sale UK | Species & buying enquiries','Considering parrots for sale in the UK? Explore eight groups, ask about individual availability and prepare a considered buying enquiry.','UK PARROT BUYING ENQUIRIES','A better beginning<br>starts with better questions.','Explore parrots for UK homes and prepare a considered enquiry. Individual birds, prices and availability are confirmed directly.',blocks([('Looking for parrots for sale in the UK?','<p>Begin by comparing species and practical needs. Crownwing’s collection covers African parrots, macaws, cockatoos, Amazons, conures, caiques, Eclectus and parakeets. Our commercial pages explain what to ask about each group before deciding on a particular bird.</p><p>This website does not show live stock or publish unconfirmed prices. Representative photographs introduce species. Use the enquiry pages to request details about actual birds and proposed arrangements.</p>')])+linkcards(sales)+blocks([('What a useful buying enquiry includes','<p>Tell us which species interests you, your bird-keeping experience, the accommodation you can provide and your typical routine. Include questions about the individual’s age, diet, background, behaviour and records. Explain whether other birds or animals share your home.</p><p>Review the '+a('/guides/buying-a-parrot-checklist/','buying checklist')+' and '+a('/guides/parrot-ownership-costs/','ownership costs')+' before committing. Our '+a('/our-approach/','approach')+' puts practical suitability at the centre of the conversation.</p>'),('Confirm availability, price and arrangements','<p>Request current details of the individual bird. Confirm the price and what is included, relevant terms, any viewing opportunity and handover arrangements. Collection or delivery should only be assumed once agreed.</p><p>Direct contact details will be added when supplied by the business. You can currently prepare and download an enquiry to keep ready for that conversation.</p>')])+cta('Prepare your UK parrot enquiry')+related([('/parrots/','Species & care profiles'),('/guides/choosing-a-parrot/','Choosing the right bird'),('/contact/','Enquiries')]))
form=re.search(r'<form id="enquiry-form">.*?</form>',home,re.S).group()
page('/contact/','Contact & parrot enquiries UK','Prepare a Crownwing Parrots enquiry about species, suitability, individual availability and care. Keep a downloadable copy ready to share.','LET’S BEGIN WITH A CONVERSATION','Tell us about your home.<br>And your next companion.','Share the species that interests you, your experience and the practical questions you need answered.',f'<section class="contact-layout"><div><h2>Prepare your enquiry</h2><p>Include your routine, available space and any birds you already keep. Request current photographs, diet information, health records, prices and proposed arrangements for an individual bird.</p><p>Direct email and telephone details will be added shortly. This form prepares a downloadable copy; it does not send your details or store them.</p><p>Before enquiring, read {a("/our-approach/","our approach")} and the {a("/guides/buying-a-parrot-checklist/","buying checklist")}.</p></div><div class="contact-form-panel">{form}</div></section>'+related([('/parrots/','Find a species'),('/parrots-for-sale/','Buying enquiries'),('/parrot-care/','Care library')]))

# Connect the existing species guides to commercial and educational pages.
for d,(sale_path,_) in zip(data,sales):
 p=out/'parrots'/d['slug']/'index.html';s=(root/'tools/templates'/d['slug']/'index.html').read_text();s=re.sub(r'<header>.*?</header>',header,s,flags=re.S);s=re.sub(r'<footer\b[^>]*>.*?</footer>',footer,s,flags=re.S)
 s=s.replace('/?species='+d['slug']+'#enquire','/contact/?species='+d['slug'])
 s=s.replace('href="/#parrots"','href="/parrots/"')
 links=blocks([('Considering this group for your home?',f'<p>Read the {a(sale_path,d["name"].lower()+" UK buying enquiry page")} for questions about the individual bird, price and availability. For preparation, explore {a("/guides/parrot-diet-nutrition/","diet and nutrition")}, {a("/guides/parrot-housing-enrichment/","housing and enrichment")} and the {a("/guides/buying-a-parrot-checklist/","buying checklist")}.</p>')])
 s=s.replace('<div class="guide-sources">',links+'<div class="guide-sources">');p.write_text(s)

# Replace homepage scroll-only navigation and oversized information blocks with page teasers.
home=re.sub(r'<header>.*?</header>',header,home,flags=re.S);home=re.sub(r'<footer\b[^>]*>.*?</footer>',footer,home,flags=re.S)
home=home.replace('href="#approach"','href="/our-approach/"').replace('href="#parrots"','href="/parrots/"')
home=re.sub(r'<section id="approach".*?</section>', '<section class="home-feature section"><div><p class="eyebrow">THE CROWNWING APPROACH</p><h2>A companion.<br>A commitment.<br>A considered choice.</h2></div><div><p>Choosing a parrot starts with your home, your routine and the bird’s needs. Discover the questions behind a thoughtful match.</p><a class="button" href="/our-approach/">Read our approach</a></div></section>',home,flags=re.S)
home=re.sub(r'<section id="care".*?</section>', '<section class="section"><div class="section-heading"><div><p class="eyebrow">BEFORE THE FIRST HELLO</p><h2>Research the bird.<br>Prepare the home.</h2></div><p>Explore practical guides to choosing a parrot, everyday care and the commitments behind a good beginning.</p></div>'+linkcards(guidelinks[:3])+f'<p class="hub-link">{a("/parrot-care/","Explore the full parrot care library")}</p></section>',home,flags=re.S)
home=re.sub(r'<section class="enquiry section".*?</section>', '<section class="enquiry section"><div><p class="eyebrow">PARROTS FOR UK HOMES</p><h2>Your next chapter<br>could have <em>wings.</em></h2><p>Explore species-specific buying enquiries, understand the care commitment and request information about the individual bird.</p></div><div><a class="button lime" href="/parrots-for-sale/">Explore UK buying enquiries</a><p><a class="text-link" href="/contact/">Prepare an enquiry</a></p></div></section>',home,flags=re.S)
home=home.replace('<title>Crownwing Parrots | A world of extraordinary birds</title>','<title>Crownwing Parrots UK | Species & Buying Enquiries</title>').replace('Explore African parrots, macaws, cockatoos, Amazons, conures, caiques, Eclectus and parakeets with Crownwing Parrots.','Explore parrots for UK homes with species guides, buying enquiries and practical care information from Crownwing Parrots.')
home=home.replace('<script src="app.js"></script>','<script src="/common.js"></script>');(out/'index.html').write_text(home)

# One shared header interaction; enquiry behaviour only runs on the contact page.
app=(out/'app.js').read_text();app=app.replace('document.getElementById("species-select");speciesNames','document.getElementById("species-select");speciesNames')
menu=app[app.index('const menu='):app.index("document.getElementById('enquiry-form').onsubmit")]
enquiry=app[:app.index('const menu=')]+app[app.index("document.getElementById('enquiry-form').onsubmit"):]
(out/'common.js').write_text(menu+'\nif(document.getElementById("enquiry-form")){\n'+enquiry+'\n}\n')

# Set unique canonical metadata and descriptive breadcrumbs throughout the static site.
paths=[]
for p in sorted(out.rglob('index.html')):
 rel=p.parent.relative_to(out).as_posix();path='/' if rel=='.' else '/'+rel+'/'
 paths.append(path);s=p.read_text();s=re.sub(r'<link rel="canonical"[^>]*>','',s)
 s=re.sub(r'<script type="application/ld\+json">.*?</script>','',s,flags=re.S)
 title=re.search(r'<title>(.*?)</title>',s).group(1);title=html.unescape(title)
 schema={'@context':'https://schema.org','@type':'WebPage','name':title,'url':origin+path,'isPartOf':{'@type':'WebSite','name':'Crownwing Parrots','url':origin+'/'}}
 if path!='/':schema['breadcrumb']={'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':origin+'/'},{'@type':'ListItem','position':2,'name':title.split('|')[0].strip(),'item':origin+path}]}
 s=s.replace('</head>',f'<link rel="canonical" href="{origin+path}"><script type="application/ld+json">{json.dumps(schema)}</script></head>');p.write_text(s)
from xml.sax.saxutils import escape
(out/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+escape(origin+path)+'</loc></url>' for path in paths)+'</urlset>')
(out/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+origin+'/sitemap.xml\n')
print(f'Created connected content architecture: {len(paths)} pages, canonical URLs, breadcrumbs and sitemap.')

# Apply the current visible-copy preference after regenerating pages.
import runpy as _notice_runner
_notice_runner.run_path(str(root/'tools/clean-visible-notices.py'))
import subprocess, sys
subprocess.run([sys.executable, str(root/'tools/populate-photos.py')], check=True)
subprocess.run([sys.executable, str(root/'tools/apply-breeder-positioning.py')], check=True)
